# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourbest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('hot', models.BooleanField()),
                ('available_count', models.IntegerField()),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('style_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourbest.Style')),
            ],
        ),
        migrations.AddField(
            model_name='bookings',
            name='tour_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourbest.Tour'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourbest.UserProfile'),
        ),
    ]
