# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourbest', '0003_tour_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sales_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
