# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourbest', '0005_auto_20160102_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='tour_id',
            new_name='tour',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='user_id',
            new_name='user',
        ),
    ]
