# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 12:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tourbest', '0006_auto_20160102_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='contact_phone',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
    ]
